# Start time: 10:46
# End time: 11:39

import aocd, collections, itertools

data = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""

# data = """..........
# ..........
# ..........
# ....a.....
# ........a.
# .....a....
# ..........
# ..........
# ..........
# .........."""

data = aocd.get_data(year=2024, day=8)

coords = collections.defaultdict(list)
height, width = len(data.split()), len(data.split()[0])
for y, row in enumerate(data.split()):
    for x, char in enumerate(row):
        coords[char] += [(x, y)] if char not in ".#" else []


def get_antinodes(nodes: list[tuple[int, int]]):
    antinodes = []
    for (x1, y1), (x2, y2) in itertools.permutations(nodes, 2):
        antinodes.append((x2 + (x2 - x1), y2 + (y2 - y1)))
    return antinodes


anti_nodes = set()
for char, nodes in coords.items():
    for x, y in get_antinodes(nodes):
        if 0 <= x < width and 0 <= y < height:
            anti_nodes.add((x, y))

print(len(anti_nodes))
